/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package JDesktopPane;

import Clases.ConexionBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author lypef_000
 */
public class AddCliente extends javax.swing.JInternalFrame {
    int compara;
    String TipoUser,Turno;
    int id = 1;
    /**
     * Creates new form AddStaff
     */
    public AddCliente() {
        initComponents();
        setTitle("Agregar personal");
        id();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumeroID1 = new javax.swing.JLabel();
        NumeroID = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SegundoApellido = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BotonCancelar = new javax.swing.JButton();
        BotonDarDeAlta = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RFC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PrimerApellido = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        NumeroID1.setForeground(new java.awt.Color(255, 0, 0));
        NumeroID1.setText("Nuevo ID :");

        NumeroID.setForeground(new java.awt.Color(255, 0, 0));
        NumeroID.setText("ID");

        jLabel11.setText("Ingrese datos del nuevo cliente");

        jLabel12.setText("Primer apellido");

        jLabel1.setText("Nombre");

        BotonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancel.png"))); // NOI18N
        BotonCancelar.setText("Cancelar");
        BotonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        BotonDarDeAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save.png"))); // NOI18N
        BotonDarDeAlta.setText("Guardar");
        BotonDarDeAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonDarDeAlta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDarDeAltaActionPerformed(evt);
            }
        });

        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clean.png"))); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        jLabel3.setText("Segundo apellido");

        jLabel4.setText("Telefono");

        jLabel5.setText("Direccion");

        jLabel9.setText("RFC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(NumeroID1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumeroID))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Direccion)
                                        .addComponent(Telefono)
                                        .addComponent(SegundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                        .addComponent(RFC, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(PrimerApellido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeroID)
                            .addComponent(NumeroID1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonDarDeAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        Limpiar();
        dispose();   
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDarDeAltaActionPerformed
        Nombre.setText(Nombre.getText().toUpperCase());
        PrimerApellido.setText(PrimerApellido.getText().toUpperCase());
        SegundoApellido.setText(SegundoApellido.getText().toUpperCase());
        Direccion.setText(Direccion.getText().toUpperCase());
        RFC.setText(RFC.getText().toUpperCase());
        if (Nombre.getText().equals("") || PrimerApellido.getText().equals("") || SegundoApellido.getText().equals("") || 
                Telefono.getText().equals("") || Direccion.getText().equals("") || RFC.getText().equalsIgnoreCase("")){
            JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Rellene todos los campos");
        }else {
            try {
                String busca = "";
                ConexionBD BD;
                String sql = "select * from cliente where nombre ='"+Nombre.getText()+"';";
                try {
                    BD = new ConexionBD ();
                    ResultSet Ingresa = BD.Consulta(sql);
                    while (Ingresa.next()){
                        busca = Ingresa.getString(2);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (Nombre.getText().equalsIgnoreCase(busca)){
                    JOptionPane.showMessageDialog(null,"Este usuario ya existe intente con otro");
                }else{
                String ID = "INSERT INTO `cliente`(`idcliente`,`nombre`, `apellidopaterno`, `apellidomaterno`, `rfc` , `telefono`,`direccion`,"
                        + "`numerodecompras`) VALUES ('"+Integer.parseInt(NumeroID.getText())+"','"+Nombre.getText()+"','"+PrimerApellido.getText()+"',"
                        + "'"+SegundoApellido.getText()+"','"+RFC.getText()+"','"+Telefono.getText()+"','"+Direccion.getText()+"',"
                        + "'"+NumeroDeCompras()+"')";
                 
                        try {
                            BD = new ConexionBD ();
                            id();
                            BD.ejecutar(ID);
                            Limpiar ();
                            dispose();
                            JOptionPane.showInternalMessageDialog(Desktop.Escritorio,"El cliente "+ Nombre.getText() + " ha sido registrado CORRECTAMENTE ");
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Ho - ho ! Algo salio mal, intentelo de nuevo");
                        } catch (SQLException ex) {
                            Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Ho - ho ! Algo salio mal, intentelo de nuevo");
                        } catch (InstantiationException ex) {
                            Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Ho - ho ! Algo salio mal, intentelo de nuevo");
                        } catch (IllegalAccessException ex) {
                            Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Ho - ho ! Algo salio mal, intentelo de nuevo");
                        }
                        }} catch (SQLException ex) {
                    Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Ho - ho ! Algo salio mal, intentelo de nuevo");
                }
            }

    }//GEN-LAST:event_BotonDarDeAltaActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        Limpiar ();
    }//GEN-LAST:event_BotonLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonDarDeAlta;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel NumeroID;
    private javax.swing.JLabel NumeroID1;
    private javax.swing.JTextField PrimerApellido;
    private javax.swing.JTextField RFC;
    private javax.swing.JTextField SegundoApellido;
    private javax.swing.JTextField Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
private void Limpiar () {
    Nombre.setText("");
    PrimerApellido.setText("");
    SegundoApellido.setText("");
    Telefono.setText("");
    Direccion.setText("");
    RFC.setText("");
    }
private void id (){

        for (;id != compara ; ){
        try {
            Clases.ConexionBD  conexion = new Clases.ConexionBD ();
            String sql = "select * from cliente where idcliente ='"+id+"';";
            ResultSet Ingresa = conexion.Consulta(sql);
   
            while (Ingresa.next()){
            compara = Ingresa.getInt(1);
            }
            if (id == compara){
            id ++;
            }else {
            NumeroID.setText(String.valueOf(id));
            break;
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AddCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        }
}
private int NumeroDeCompras ()
{
return 2;
}
}
