/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JDesktopPane;

import java.awt.event.KeyEvent;
import static java.lang.Math.random;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lypef
 */
public class addproduct extends javax.swing.JInternalFrame {

    /**
     * Creates new form addproduct
     */
    public addproduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnExit = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        TxtProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtCodigoBarra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtPrecio = new javax.swing.JTextField();
        TxtDescripcion = new javax.swing.JTextField();
        TxtStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        GenerateCodigoDeBarra = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit-Exit.png"))); // NOI18N
        BtnExit.setText("Salir");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 316, 153, 59));

        BtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AddBD.png"))); // NOI18N
        BtnAdd.setText("Registrar");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 316, 153, 59));

        TxtProducto.setBackground(new java.awt.Color(254, 254, 254));
        getContentPane().add(TxtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 34, 308, -1));

        jLabel1.setText("Producto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 40, -1, -1));

        jLabel2.setText("Descripcion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 110, -1, -1));

        TxtCodigoBarra.setBackground(new java.awt.Color(254, 254, 254));
        TxtCodigoBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCodigoBarraKeyPressed(evt);
            }
        });
        getContentPane().add(TxtCodigoBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 222, 308, -1));

        jLabel3.setText("Codigo de barra:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 228, -1, -1));

        jLabel4.setText("Precio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 183, -1, -1));

        TxtPrecio.setBackground(new java.awt.Color(254, 254, 254));
        getContentPane().add(TxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 177, 308, -1));

        TxtDescripcion.setBackground(new java.awt.Color(254, 254, 254));
        getContentPane().add(TxtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 79, 308, 86));

        TxtStock.setBackground(new java.awt.Color(254, 254, 254));
        TxtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtStockKeyPressed(evt);
            }
        });
        getContentPane().add(TxtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 261, 308, -1));

        jLabel5.setText("Stock:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 267, -1, -1));

        GenerateCodigoDeBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/codebar.png"))); // NOI18N
        GenerateCodigoDeBarra.setText("Generar");
        GenerateCodigoDeBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateCodigoDeBarraActionPerformed(evt);
            }
        });
        getContentPane().add(GenerateCodigoDeBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 316, 153, 59));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        dispose();
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        ChangeToCapital();
        if (!TxtProducto.getText().isEmpty() && !TxtDescripcion.getText().isEmpty() 
         && !TxtCodigoBarra.getText().isEmpty() && !TxtPrecio.getText().isEmpty() && !TxtStock.getText().isEmpty())
        {
            AddDates();
            Clean();
            JOptionPane.showInternalMessageDialog(Desktop.Escritorio,"Producto agregado");
        }
        else
        {
            JOptionPane.showInternalMessageDialog(Desktop.Escritorio,"Rellene todos los campos");            
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void TxtCodigoBarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCodigoBarraKeyPressed
     
    }//GEN-LAST:event_TxtCodigoBarraKeyPressed

    private void TxtStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtStockKeyPressed
    if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        { 
            BtnAdd.doClick();
        }          
    }//GEN-LAST:event_TxtStockKeyPressed

    private void GenerateCodigoDeBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateCodigoDeBarraActionPerformed
        GenerateCodigoDeBarra();
        while (true) 
        {            
           if (TxtCodigoBarra.getText().charAt(0) != 0 && CodeBarExiste() == false)
           {
               break;
           }else
           {
                GenerateCodigoDeBarra();
           }
        }
    }//GEN-LAST:event_GenerateCodigoDeBarraActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton GenerateCodigoDeBarra;
    private javax.swing.JTextField TxtCodigoBarra;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JTextField TxtProducto;
    private javax.swing.JTextField TxtStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private void ChangeToCapital() 
    {
        TxtProducto.setText(TxtProducto.getText().toUpperCase());
        TxtDescripcion.setText(TxtDescripcion.getText().toUpperCase());
        TxtPrecio.setText(TxtPrecio.getText().replace(" ", ""));
        TxtPrecio.setText(TxtPrecio.getText().replace(",","."));
        TxtCodigoBarra.setText(TxtCodigoBarra.getText().replace(" ", ""));
    }

    private void AddDates() 
    {
        try {
           
            Clases.ConexionBD coneccion = new Clases.ConexionBD();
            
            String insert = "INSERT INTO `calzado`(`producto`,`descripcion`, `codigo`, `precio`, `stock`,`vendidos` ) "
                    + "VALUES "
                    + "('"+TxtProducto.getText()+"','"+TxtDescripcion.getText()+"','"+TxtCodigoBarra.getText()+"','"+Float.parseFloat(TxtPrecio.getText())+"','"+Integer.parseInt(TxtStock.getText())+"','"+"0"+"')";
                 coneccion.ejecutar(insert);
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addproduct.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showInternalMessageDialog(Desktop.Escritorio,"Error");
        } catch (SQLException ex) {
            Logger.getLogger(addproduct.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showInternalMessageDialog(Desktop.Escritorio,"Error");
        } catch (InstantiationException ex) {
            Logger.getLogger(addproduct.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showInternalMessageDialog(Desktop.Escritorio,"Error");
        } catch (IllegalAccessException ex) {
            Logger.getLogger(addproduct.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showInternalMessageDialog(Desktop.Escritorio,"Error");
        }
    }

    private void Clean() 
    {
        TxtProducto.setText("");
        TxtDescripcion.setText("");
        TxtCodigoBarra.setText("");
        TxtPrecio.setText("");
        TxtStock.setText("");
    }
    
    private boolean CodeBarExiste ()
    {
        boolean var = false;  
        try {
            Clases.ConexionBD Coneccion = new Clases.ConexionBD();
            String sql = "select * from calzado";
            ResultSet rs = Coneccion.Consulta(sql);
           
            
            while (rs.next())
            {
                if (rs.getString(4) == TxtCodigoBarra.getText().replace(" ",""))
                {
                    var = true;
                }
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addproduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(addproduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(addproduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(addproduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        return var;
    }
    
   
    private void GenerateCodigoDeBarra() 
    {
        Random numero = new Random ();
        String cadena = "";
        for (int i = 0; i < 5; i++)
        {
            cadena += String.valueOf(numero.nextInt(10));
        }
        TxtCodigoBarra.setText(cadena);
    }
}
