/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package JDesktopPane;

import Clases.ConexionBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author lypef_000
 */
public class AddStaff extends javax.swing.JInternalFrame {
    int compara;
    String TipoUser,Turno;
    int id = 1;
    /**
     * Creates new form AddStaff
     */
    public AddStaff() {
        initComponents();
        setTitle("Agregar personal");
        id();
        ValoresCombobox ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumeroID1 = new javax.swing.JLabel();
        NumeroID = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JcomboboxNivel = new javax.swing.JComboBox();
        ConfirmaContraseña = new javax.swing.JPasswordField();
        Contraseña = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        ApellidoMaterno = new javax.swing.JTextField();
        ApellidoPaterno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonCancelar = new javax.swing.JButton();
        BotonDarDeAlta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        BotonLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JcomboboxTurno = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);

        NumeroID1.setForeground(new java.awt.Color(255, 0, 0));
        NumeroID1.setText("Nuevo ID :");

        NumeroID.setForeground(new java.awt.Color(255, 0, 0));
        NumeroID.setText("ID");

        jLabel11.setText("Ingrese los datos del trabajador.");

        JcomboboxNivel.setEditable(true);
        JcomboboxNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboboxNivelActionPerformed(evt);
            }
        });

        jLabel12.setText("Confirme Contraseña");

        jLabel2.setText("Contraseña");

        jLabel1.setText("Nombre de usuario");

        BotonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancel.png"))); // NOI18N
        BotonCancelar.setText("Cancelar");
        BotonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        BotonDarDeAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save.png"))); // NOI18N
        BotonDarDeAlta.setText("Guardar");
        BotonDarDeAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonDarDeAlta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDarDeAltaActionPerformed(evt);
            }
        });

        jLabel8.setText("E-mail");

        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clean.png"))); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Primer apellido");

        jLabel7.setText("Telefono");

        jLabel5.setText("Segundo apellido");

        jLabel6.setText("Direccion");

        JcomboboxTurno.setEditable(true);
        JcomboboxTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboboxTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NumeroID1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumeroID))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ConfirmaContraseña)
                                    .addComponent(Email)
                                    .addComponent(Telefono)
                                    .addComponent(Direccion)
                                    .addComponent(ApellidoMaterno)
                                    .addComponent(ApellidoPaterno)
                                    .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Usuario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Contraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JcomboboxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JcomboboxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeroID)
                            .addComponent(NumeroID1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcomboboxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JcomboboxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonDarDeAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JcomboboxNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboboxNivelActionPerformed
        JComboBox x = (JComboBox)evt.getSource();
        String root = "Root";
        String admin = "Administrador";
        String Vende = "Vendedor";
        String str  = (String)x.getSelectedItem();

        if (x.getSelectedItem().equals(root)){
            TipoUser = root;

        }else {
            if (x.getSelectedItem().equals(admin)){
                TipoUser = admin;
            }else {
                if(x.getSelectedItem().equals(Vende)){
                    TipoUser = Vende;
                }else {
                    TipoUser = "Null";
                }
            }

        }
    }//GEN-LAST:event_JcomboboxNivelActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        dispose();   
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDarDeAltaActionPerformed
        Usuario.setText(Usuario.getText().toUpperCase());
        Nombre.setText(Nombre.getText().toUpperCase());
        ApellidoPaterno.setText(ApellidoPaterno.getText().toUpperCase());
        ApellidoMaterno.setText(ApellidoMaterno.getText().toUpperCase());
        Direccion.setText(Direccion.getText().toUpperCase());
        
        if (Usuario.getText().equals("") || Contraseña.equals("") || ConfirmaContraseña.getText().equals("") || Nombre.getText().equals("") || 
                ApellidoPaterno.getText().equals("") || ApellidoMaterno.getText().equals("") || Direccion.getText().equals("") || Telefono.getText().equals("") 
                ||  Email.getText().equals("") || Turno.equalsIgnoreCase("") || TipoUser.equalsIgnoreCase("")){
            JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Rellene todos los campos");
        }else {
            try {
                String busca = "";
                ConexionBD BD;
                String sql = "select * from vendedor where usuario ='"+Usuario.getText()+"';";
                try {
                    BD = new ConexionBD ();
                    ResultSet Ingresa = BD.Consulta(sql);
                    while (Ingresa.next()){
                        busca = Ingresa.getString(1);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (Usuario.getText().equalsIgnoreCase(busca)){
                    JOptionPane.showMessageDialog(null,"Este usuario ya existe intente con otro");
                }else{
                    if (Contraseña.getText().equals(ConfirmaContraseña.getText())){
                        String ID = "INSERT INTO `vendedor`(`idvendedor`,`usuario`, `contraseña`, `nombre`, `apellidopaterno` , `apellidomaterno`,`direccion`,`telefono`,`turno`,`email`,`nivel`) VALUES ('"+id+"','"+Usuario.getText()+"','"+Contraseña.getText()+"','"+Nombre.getText()+"','"+ApellidoPaterno.getText()+"','"+ApellidoMaterno.getText()+"','"+Direccion.getText()+"','"+Telefono.getText()+"','"+Turno+"','"+Email.getText()+"','"+TipoUser+"')";
                 
                        try {
                            BD = new ConexionBD ();
                            id();
                            BD.ejecutar(ID);
                            Limpiar ();
                            dispose();
                            JOptionPane.showInternalMessageDialog(Desktop.Escritorio,"El trabajador "+ Nombre.getText() + " ha sido registrado CORRECTAMENTE ");
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Ho - ho ! Algo salio mal, intentelo de nuevo");
                        } catch (SQLException ex) {
                            Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Ho - ho ! Algo salio mal, intentelo de nuevo");
                        } catch (InstantiationException ex) {
                            Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Ho - ho ! Algo salio mal, intentelo de nuevo");
                        } catch (IllegalAccessException ex) {
                            Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Ho - ho ! Algo salio mal, intentelo de nuevo");
                        }
                    }else {
                        JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Verifique que las contraseñan sean las mismas");
                    }
                }} catch (SQLException ex) {
                    Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showInternalMessageDialog(Desktop.Escritorio, "Ho - ho ! Algo salio mal, intentelo de nuevo");
                }
            }

    }//GEN-LAST:event_BotonDarDeAltaActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        Limpiar ();
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void JcomboboxTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboboxTurnoActionPerformed
        JComboBox x = (JComboBox)evt.getSource();
        String Matutino = "Matutino";
        String Vespertino = "Vespertino";
        String str  = (String)x.getSelectedItem();

        if (x.getSelectedItem().equals(Matutino)){
            Turno = Matutino;

        }else {
            if (x.getSelectedItem().equals(Vespertino)){
                Turno = Vespertino;
            }else
            {
            Turno = "null";
            }
        }
    }//GEN-LAST:event_JcomboboxTurnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoMaterno;
    private javax.swing.JTextField ApellidoPaterno;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonDarDeAlta;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JPasswordField ConfirmaContraseña;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Email;
    private javax.swing.JComboBox JcomboboxNivel;
    private javax.swing.JComboBox JcomboboxTurno;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel NumeroID;
    private javax.swing.JLabel NumeroID1;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
private void Limpiar () {
    Usuario.setText("");
    Contraseña.setText("");
    ConfirmaContraseña.setText("");
    Nombre.setText("");
    ApellidoPaterno.setText("");
    ApellidoMaterno.setText("");
    Direccion.setText("");
    Telefono.setText("");
    Email.setText("");
    Telefono.setText("");
    }
private void id (){

        for (;id != compara ; ){
        try {
            Clases.ConexionBD  conexion = new Clases.ConexionBD ();
            String sql = "select * from vendedor where idvendedor ='"+id+"';";
            ResultSet Ingresa = conexion.Consulta(sql);
   
            while (Ingresa.next()){
            compara = Ingresa.getInt(1);
            }
            if (id == compara){
            id ++;
            }else {
            NumeroID.setText(String.valueOf(id));
            break;
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        }
}

    private void ValoresCombobox() 
    {
        JcomboboxTurno.addItem("Seleccion el turno");
        JcomboboxTurno.addItem("Matutino");
        JcomboboxTurno.addItem("Vespertino");
        JcomboboxNivel.addItem("Seleccione el nivel");
        JcomboboxNivel.addItem("Root");
        JcomboboxNivel.addItem("Administrador");
        JcomboboxNivel.addItem("Vendedor");
    }
}
