/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JDesktopPane;
import Clases.functions;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author lypef
 */
public class familys extends javax.swing.JInternalFrame {

    /**
     * Creates new form creditos
     */
    
    functions f = new functions();
    
    public familys() {
        initComponents();
        f.Familys_Get(Tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtDescripcion = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(942, 561));

        Tabla.setFont(Tabla.getFont());
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de familia");

        jLabel2.setText("Descripcion de familia");

        TxtNombre.setMaximumSize(new java.awt.Dimension(50, 39));
        TxtNombre.setMinimumSize(new java.awt.Dimension(50, 39));
        TxtNombre.setPreferredSize(new java.awt.Dimension(50, 39));

        TxtDescripcion.setColumns(20);
        TxtDescripcion.setRows(5);
        TxtDescripcion.setMaximumSize(new java.awt.Dimension(343, 38));
        TxtDescripcion.setMinimumSize(new java.awt.Dimension(343, 38));
        TxtDescripcion.setPreferredSize(null);
        jScrollPane2.setViewportView(TxtDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (f.Family_Add(TxtNombre, TxtDescripcion))
        {
            f.Familys_Get(Tabla);
            f.Alert("Familia agregada", functions.Alert_Informacion);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMousePressed
        if (evt.getClickCount() == 2)
        {
            int id = Integer.parseInt((String) f.Lista_Familia.get(Tabla.getSelectedRow()));
            
            ButtonGroup Group = new ButtonGroup();

            
            JCheckBox chec0 = new JCheckBox("Ninguno");
            Group.add(chec0);
            chec0.setSelected(true);
            
            
            JCheckBox chec1 = new JCheckBox("Editar");
            Group.add(chec1);
            
            
            JCheckBox chec2 = new JCheckBox("Eliminar");
            Group.add(chec2);
            
           
            int seleccion = JOptionPane.showOptionDialog( this,"Sleccione una opcion",
                "EDICION FAMILIA",JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE,null,
                new Object[] { "ACEPTAR",chec0, chec1, chec2},"ACEPTAR");

            if (chec1.isSelected()){
                f.Familys_Get(Tabla);
            }
            
            if (chec2.isSelected())
            {
                if (JOptionPane.showConfirmDialog(rootPane,"¿Eliminar elemento?","Eliminar",0, functions.Alert_Warning)==0)
                {
                    if (f.Family_Delete(id))
                    {
                        f.Familys_Get(Tabla);
                        f.Alert("Familia eliminada", functions.Alert_Informacion);
                    }
                }
                
                
            }

            
        }
    }//GEN-LAST:event_TablaMousePressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JTextArea TxtDescripcion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
}
